### PR TITLE
yoda condition and identical comparison added

### PR DESCRIPTION
**Pull request by ismail1432**
Just added a Comparison part with Yoda condition and Identical comparison

### CODE REVIEW

**Comment by peter-gribanov** [comment]
Identical comparison is not always necessary and sometimes even harmful.

[Example](https://3v4l.org/uW5VT):

```php
$date1 = new DateTime('01-01-2017');
$date2 = clone $date1;

var_dump($date1 === $date2); // bool(false)
var_dump($date1 == $date2); // bool(true)
```

I understand the use of Yoda condition, but i do not like this code style. Maynteiner may not agree with me.

**Comment by ismail1432** [comment]
Thanks for the feed back ☺️

**Comment by TomasVotruba** [comment]
Could you please decouple strict comparison to standalone PR?
I consider it useful.

**Comment by ismail1432** [comment]
Yep I will do... 🙂

**Comment by ismail1432** [comment]
Done ✅

**Comment by TomasVotruba** [comment]
Thanks. Could you add 2 examples in code where it would into error?


Also, please try to keep coding standard as in other code.

**Comment by ismail1432** [comment]
Done #2 😝

**Comment by peter-gribanov** [comment]
How about something more not obvious?

```php
var_dump(100 == "1e2"); // bool(true)
var_dump(12 == 014); // bool(true)
var_dump(0 == "0,9"); // bool(true)
var_dump(233 == "233w1"); // bool(true)
var_dump("2.0000000000000000123" == "2.0000000000000000456"); // bool(true)
```

https://3v4l.org/EIVdY

**Comment by TomasVotruba** [comment]
Rather than obvious code like 1 == true, what about adding some emotions? Something from practise would be great. Code that failed you and caused a real bug, that was hard to find.

**Comment by TomasVotruba** [comment]
Merging this as good new rule was added and not related to origin name of PR.

Thank you!

**Comment by ismail1432** [comment]
👌🏽 
Thank you for this work

**Comment by TomasVotruba** [comment]
You did great work - thank you!

**Pull request merged**
