### PR TITLE
这个翻译的有问题啊

### PR DESCRIPTION
**Pull request by linjialiang**
> 中文乱组了，你查看下

default

### CODE REVIEW

**Comment by Ferikl** [comment]
@linjialiang can you translate some key points to English, just to keep your work more international

**Comment by linjialiang** [comment]
> I'd love to, but I'm always worried about mistakes in translation

**Comment by peter-gribanov** [comment]
You should save the translation only in your repository and add a link to it in [the Translations section](https://github.com/jupeter/clean-code-php#translations).
See example [here](https://github.com/jupeter/clean-code-php/pulls?utf8=%E2%9C%93&q=is%3Apr+translate).

**Comment by peter-gribanov** [comment]
If you have corrections in the translation into Chinese, create PR in [the Chinese translation repository](https://github.com/php-cpm/clean-code-php).

**Comment by linjialiang** [comment]
> Ok, let me try

**Comment by TomasVotruba** [comment]
Closing as answered

**Pull request closed without merging**
