### PR TITLE
Fix build issues

### PR DESCRIPTION
**Pull request by Slamdunk**
- [ ] Travis, do you listen?
- [ ] Fix build issues

### CODE REVIEW

**Comment by Slamdunk** [comment]
@jupeter or @TomasVotruba ping me when you are ready, I'll push other fake commits if needed

**Comment by TomasVotruba** [comment]
I don't have admin access, so @jupeter has to check this

**Comment by peter-gribanov** [comment]
@jupeter ping

**Comment by TomasVotruba** [comment]
Closing as unfinishable without attention

**Pull request closed without merging**
