### PR TITLE
Avoid nesting too deeply and return early

### PR DESCRIPTION
**Pull request by jewei**
Add reason and examples.

### CODE REVIEW

**Comment by peter-gribanov** [comment]
A bad example, it is always bad, but a good example is also not good.
Your `checkEmailExist()` function violates the [SRP principle](https://github.com/jupeter/clean-code-php#single-responsibility-principle-srp).

**Comment by TomasVotruba** [comment]
@jewei I missed this rule here. Thank you

@peter-gribanov How would you improve `checkEmailExist` then?

**Comment by peter-gribanov** [comment]
@TomasVotruba Verification of user input must be performed in controller or in validator.
Checking availability of email is a business transaction and it should be in a model.

So, it maybe look like this:

```php
// this code in controller

if (!isset($_POST['action'], $_POST['email'], $_POST['user_id'])) {
    // show verification error message...
}

$user = User::find($_POST['user_id']);

// is validation too
if (!$user instanceof User) {
    // show error message what user is not found...
}

// here is begins Use Case
if ($user->hasEmail($_POST['email'])) {
    // do what you need...
}
```

**Comment by jewei** [comment]
Updated with slightly better code examples 😅

**Comment by peter-gribanov** [comment]
Great job. Thanks :+1:

**Comment by TomasVotruba** [comment]
Thank you

**Comment by MaxChew** [comment]
Very good job.. but i think still got space for improving.

**Comment by TomasVotruba** [comment]
Feel free to send PR

**Pull request merged**
