### PR TITLE
Fix example for Prefer composition over inheritance

### PR DESCRIPTION
**Pull request by php-rock**

### CODE REVIEW

**Review by peter-gribanov — APPROVED** [review]

**Review by dusta — APPROVED** [review]

**Comment by ishan-biztech** [comment]
It's not always possible to use DI, for example framework like CakePHP doesn't use any DI container by default. So if we want to make this repo framework agnostic we should consider that people from all different frameworks can follow these best practices.

**Comment by peter-gribanov** [comment]
@ishan-biztech DI nothing to do with it. `EmployeeTaxData` is a model, not a service.

**Comment by peter-gribanov** [comment]
@TomasVotruba ping

**Review by TomasVotruba — APPROVED** [review]

**Comment by TomasVotruba** [comment]
This changes hidden factory to a setter. Good job 👍

**Pull request merged**
