### PR TITLE
Expand description of Singleton

### PR DESCRIPTION
**Pull request by peter-gribanov**
See comment https://github.com/jupeter/clean-code-php/issues/61#issuecomment-327727596
Description from https://stackoverflow.com/a/138012/2455621

This is not the best description, but it will come off for a start.

### CODE REVIEW

**Comment by dmytro-y-dev** [comment]
There are also very good thoughts by Misko Hevery (http://misko.hevery.com/about/) about the root of problem http://misko.hevery.com/2008/08/25/root-cause-of-singletons/, and he is well known in Angular community and because of his works about writing good tests and testable code (not to mention that he is Agile Coach at Google and previously worked at Adobe, Sun Microsystems, Intel, and Xerox as developer). Also, a load of information and healthy discussion in comments.

**Comment by peter-gribanov** [comment]
@metamaker Thanks. I add this link.

**Comment by TomasVotruba** [comment]
I think it would make it a bit easier to read, if **the most important parts would be highlighted**.

Could you pick like 4-5 such parts and **bold** them?

**Comment by peter-gribanov** [comment]
I highlighted the important parts.

**Comment by TomasVotruba** [comment]
Thanks, let's add it then

**Pull request merged**
