### PR TITLE
Don't repeat yourself [DRY]

### PR DESCRIPTION
**Pull request by peter-gribanov**
The [Remove duplicate code](https://github.com/jupeter/clean-code-php#remove-duplicate-code) section is a [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) principle.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thanks for the PR. Could you use more attomical commits with smaller steps, so I can see what exactly has changed?
Now it looks like 100 lines was removed and 100 was added.

**Comment by peter-gribanov** [comment]
I just moved these 100 lines to the end of the document

**Comment by peter-gribanov** [comment]
I just change the title of the section.
Move the section down the document.
And add link to Wikipedia.

**Comment by peter-gribanov** [comment]
I add fix #45 in my PR, so that there is no conflict.

**Comment by TomasVotruba** [comment]
@peter-gribanov If that's the case, let's merge it then. Thank you for info and the code update

**Pull request merged**
