### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by EDDYMENS**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thank you man

**Comment by EDDYMENS** [comment]
I want to know if its possible to rephrase the word `bad` to something much more neutral. For some of the examples the so called `bad` is not exactly bad just that there are better ways of going about them.

**Comment by TomasVotruba** [comment]
I see what you mean. What wording would you pick?

**Comment by EDDYMENS** [comment]
Still thinking of a word, but I think `poor` is ok ?

**Pull request merged**
