### PR TITLE
Interface Segregation Principle (ISP)

### PR DESCRIPTION
**Pull request by peter-gribanov**
Fix for [Interface Segregation Principle (ISP)](https://github.com/jupeter/clean-code-php#interface-segregation-principle-isp).

Changes:

* Correct CS
* Rename `Worker` to `Employee`
* Rename method `Manager::setWorker()` to `Manager::subdue()`
* Manager can manage several workers
* Manager is also an employee
* Work of a manager is to force workers to work

Not every worker is an employee, but every employee is an worker.

### CODE REVIEW

**Review by TomasVotruba — COMMENTED** [review]
This quite difficult to understand even for me and I already know the principal. 
Could we make it more simple, just to show the 1 simple example?
I think Manager is not needed at all to explain it. Robot and Human will do just fine. Could we remove it?

**Comment by peter-gribanov** [comment]
Ok. I'll delete the manager.

**Comment by peter-gribanov** [comment]
It seems to me that without a manager there is less sense in all these changes.

**Comment by TomasVotruba** [comment]
I like the output. Now it's clear that bigger interface with all methods are bad practice and should be split to more specific and use them instead.

I think it's ready to merge.

**Comment by TomasVotruba** [comment]
Merging, thank you

**Pull request merged**
