### PR TITLE
Dependency Inversion Principle (DIP)

### PR DESCRIPTION
**Pull request by peter-gribanov**
Fix for [Dependency Inversion Principle (DIP)](https://github.com/jupeter/clean-code-php#dependency-inversion-principle-dip)

Сhange dependencies without changing the `Manager` code.
This is important especially if the code belongs to different components/modules.

### CODE REVIEW

**Comment by peter-gribanov** [comment]
ping @TomasVotruba

**Comment by TomasVotruba** [comment]
What does `SumeWorker` mean? Could we pick better name?

**Comment by peter-gribanov** [comment]
@TomasVotruba I renamed classes from abstract to more close to reality

**Comment by TomasVotruba** [comment]
Thank you, great job :tada: 

 I recall this is already used in other examples, so it will be more clear to readers

**Pull request merged**
