### PR TITLE
Delete "Functions should do one thing" section

### LINKED ISSUE #38: Functions should do one thing
See [Functions should do one thing](https://github.com/jupeter/clean-code-php#functions-should-do-one-thing).

Example is terrible.
My proposal for improvement was rejected #22
Need to think about how to make an example easier and better.

### PR DESCRIPTION
**Pull request by peter-gribanov**
Decided to delete section **Functions should do one thing** https://github.com/jupeter/clean-code-php/issues/38#issuecomment-532558057

---

EDIT by @TomasVotruba : Closes #38

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thanks! Just a tip for next PR to auto-close original issue on merge:

https://help.github.com/en/articles/closing-issues-using-keywords

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Comment by peter-gribanov** [comment]
> Thanks! Just a tip for next PR to auto-close original issue on merge:
> 
> https://help.github.com/en/articles/closing-issues-using-keywords

@TomasVotruba I know this, but it doesn’t always work :confused:

**Comment by TomasVotruba** [comment]
What exactly doesn't work?

"Close X" in the body of PR always worked for me for last 4 years

**Comment by peter-gribanov** [comment]
@TomasVotruba Usually works, but sometimes not. Just a week ago there were a couple of such cases.

I try to always mark the closing ticket, but sometimes i forget to do it. Sorry for this.

**Comment by TomasVotruba** [comment]
No troubles!

Ping me next time it doesn't work, I'm curious about it

**Comment by peter-gribanov** [comment]
@TomasVotruba you were interested in an example.

Bugreport created
https://github.com/Happyr/Doctrine-Specification/issues/232
2 bugfix PR were created.
First rejected
https://github.com/Happyr/Doctrine-Specification/pull/233
Second merged
https://github.com/Happyr/Doctrine-Specification/pull/234
Both PR have a link to this issue.
image
This issue did not close automatically after PR merged.
Such situations rarely occur, but they do.

image

**Comment by TomasVotruba** [comment]
Thanks for feedback.
I usually use "fixes" or "closes", not "fix". Maybe "fix" is only working in some cases. That's my random tip.

**Comment by rob006** [comment]
> This issue did not close automatically after PR merged.
> Such situations rarely occur, but they do.

Issues are closed when PR is merged to default branch in repo. It should work if you merge this PR directly to `master` branch.

https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords

**Comment by TomasVotruba** [comment]
I know what's written there. My point is documentation !== code

**Comment by rob006** [comment]
> I know what's written there. My point is documentation !== code

Can you give an example? https://github.com/Happyr/Doctrine-Specification/pull/234 did not closed issue because it was merged do `1.0` branch while default branch for this repo is `master`. It worked exactly as explained in documentation.

**Comment by peter-gribanov** [comment]
@rob006 https://github.com/Happyr/Doctrine-Specification/pull/234 merged into `1.0` branch and then branch `1.0` merged into `master` https://github.com/Happyr/Doctrine-Specification/pull/235. That is, the fix PR merged in `master`, but not immediately.

**Comment by peter-gribanov** [comment]
@rob006 although, perhaps you are right. The problem is that PR did not merge immediately into `master` and the hook in GitHub did not work. If i meet more such cases, i will describe them here.

**Comment by rob006** [comment]
@peter-gribanov I don't think that you can interpret this as "PR was merged to `master`". It works in this way for commits, because commits are included in `master` branch as a part of git tree logic (and AFAIK it should work if commit message would contain correct keyword). But PR is just an abstraction, and merge is an event that occurs once (and has only one target branch). There is no direct relation between different PRs, GitHub does not seem to track this in a way that you may expect in this case.

**Pull request merged**
