### PR TITLE
add Translation section #59

### PR DESCRIPTION
**Pull request by php-cpm**
add Translation section

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thanks for the PR.

Maybe plural title "Translations" would be better, to impli more translations are accepted.

**Comment by peter-gribanov** [comment]
Please add a link to section in [table of contents](https://github.com/jupeter/clean-code-php/pull/64/files#diff-04c6e90faac2675aa89e2176d2eec7d8R14). Thanks

```md
   7. [Translations](#translations)
```

**Comment by php-cpm** [comment]
done

**Comment by TomasVotruba** [comment]
Thank you @php-cpm

**Pull request merged**
