### PR TITLE
[ISP] Rename classes to avoid confusion

### PR DESCRIPTION
**Pull request by peter-gribanov**
Rename the classes to indicate that these are not entities in a global context.
[Some people](https://github.com/jupeter/clean-code-php/issues/147#issuecomment-380036081) have problems with this.

In a global context, an employee is a particular case of a human.
In the context of employees it will be vice versa. Human is a special case of employees.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
I missed this in my notifications.

Nice improvement :+1:  

There is actually coding standard sniff for this: https://github.com/symplify/codingstandard#class-should-have-suffix-by-parent-classinterface

**Comment by peter-gribanov** [comment]
> There is actually coding standard sniff for this: https://github.com/symplify/codingstandard#class-should-have-suffix-by-parent-classinterface

Your standards are not very good. Some of the rules seem to be borrowed from the Symfony. Some of them are anti-standards.

**Comment by TomasVotruba** [comment]
That looks like a perfect prototype of [anti-construct feedback](https://www.tomasvotruba.cz/blog/2018/03/19/how-to-criticize-like-a-senior-programmer/) :D

**Comment by peter-gribanov** [comment]
@TomasVotruba i would discuss this constructively in the project, but the issues are closed in project.
I can comment here if you are interested.

**Comment by TomasVotruba** [comment]
That's because it's [a monorepo](https://gomonorepo.org/#what-is-monorepo). 

This is the one you're looking for https://github.com/Symplify/Symplify

**Comment by peter-gribanov** [comment]
@TomasVotruba i open discuss https://github.com/Symplify/Symplify/issues/1029

**Pull request merged**
