### PR TITLE
Fix spelling under `Remove duplicate code`

### PR DESCRIPTION
**Pull request by michaelbiberich**
Rename all occurences of word `employe` (missing a second `e` at the end) to `employee`.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thanks for the fix.
Could you rebase or resend on current master? There have been some changes with content

**Comment by michaelbiberich** [comment]
I've rebased on `master` as requested. Please feel free to let me know if anything else needs to be changed.

**Comment by TomasVotruba** [comment]
It doesn't look like so. There are still many extra commits. See those various contributors above.

**Comment by michaelbiberich** [comment]
With the latest changes the referenced branch is displaed as having no conflicts with the base branch os I'm not quite sure if I've done or understood something wrong.

Regardless it seems that @peter-gribanov has already merged the relevant changes into master (see: [08c8cc7b0791ed38fc11d8dca9d442a31cb85795)](https://github.com/jupeter/clean-code-php/commit/08c8cc7b0791ed38fc11d8dca9d442a31cb85795).

Because of this I guess that this PR can be closed.

**Comment by TomasVotruba** [comment]
> With the latest changes the referenced branch is displaed as having no conflicts with the base branch os I'm not quite sure if I've done or understood something wrong.

There don't have to be conflict to mix with other people's commits.

I think our views of this PR can differ. I see it like this:

image

> Regardless it seems that @peter-gribanov has already merged the relevant changes into master (see: 08c8cc7b0791ed38fc11d8dca9d442a31cb85795).

That's great. There have been many changes and some mixed up in more PRs.

Thank you for your work anyway. Moreover for this nice note that helped to resolve this :sun_with_face:

**Pull request closed without merging**
