### PR TITLE
Column size

### PR DESCRIPTION
**Pull request by webysther**
Quote from **Clean Code** book:

"Of course we said that at a time when VT100 screens were 24 lines by 80 columns, and our editors used 4 lines for administrative purposes. Nowadays with a cranked-down font and a nice big monitor, you can fit 150 characters on a line and a 100 lines or more on a screen. Lines should not be 150 characters long. Functions should not be 100 lines long. Functions should hardly ever be 20 lines long."

More vertical code than horizontal to keep easy to read. :)

### CODE REVIEW

**Comment by peter-gribanov** [comment]
See [PSR-2](http://www.php-fig.org/psr/psr-2/#23-lines)

> There MUST NOT be a hard limit on line length; the soft limit MUST be 120 characters; lines SHOULD be 80 characters or less.

**Comment by webysther** [comment]
Well, I saw it. It is a ";" is different from a ".". As well as the rest of the text that I put to you:

>There MUST NOT be a hard limit on line length.
>
>The soft limit on line length MUST be 120 characters; automated style checkers MUST warn but MUST NOT error at the soft limit.
>
>**Lines SHOULD NOT be longer than 80 characters; lines longer than that SHOULD be split into multiple subsequent lines of no more than 80 characters each.**
>
>There MUST NOT be trailing whitespace at the end of non-blank lines.
>
>Blank lines MAY be added to improve readability and to indicate related blocks of code.
>
>There MUST NOT be more than one statement per line.

**Comment by webysther** [comment]
And it's necessary to make it clear that I'm not dictating rules or trying to enforce them, it's a matter of reading code, it's much easier to read a vertical code than a horizontal code.

**Comment by peter-gribanov** [comment]
Note also this remark:

> The soft limit on line length MUST be 120 characters; **automated style checkers MUST warn but MUST NOT error at the soft limit.**

A good explanation of these rules can be found [here](https://stackoverflow.com/a/18495354/2455621).

> And it's necessary to make it clear that I'm not dictating rules or trying to enforce them, it's a matter of reading code, it's much easier to read a vertical code than a horizontal code.

Yes, and that's why we use a string limitation of 120 characters.

**Comment by webysther** [comment]
This point I understand and believe there is no disagreement, I just do not understand the problem of adding more line break in the code. That position is unreasonable. Is not it okay to do a PR by improving it?

**Comment by TomasVotruba** [comment]
Just to sum this up, it is common to use 120 nowadays, even more.
First I was affraid this is "rise to 160 length PR", which would make more sense, though still opinionated.

Thanks for opening discussion though, it might lead into bigger change. I recommend to ask in issue in [PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer) about chaing the default value for LineLenghtSniff, which is now 120. It have much greater impact.

 Let's stick with the middle way now.

**Pull request closed without merging**
