### PR TITLE
Liskov Substitution Principle (LSP)

### PR DESCRIPTION
**Pull request by peter-gribanov**
Fix for #37

Correct **Good** example of LSP and add one more example.

### CODE REVIEW

**Comment by peter-gribanov** [comment]
@TomasVotruba What do you think about this improvement?

**Comment by peter-gribanov** [comment]
@TomasVotruba @jupeter ping

**Comment by TomasVotruba** [comment]
This PR is too long and unreadable for me. I'm unable to review correctly, I'm sorry

**Comment by peter-gribanov** [comment]
@TomasVotruba I remove **Not bad** section. Can it be easier for you to understand?

**Comment by TomasVotruba** [comment]
Still to long to decide quickly without much thought.

**Comment by peter-gribanov** [comment]
LSP is not the thing that can be quickly decide.
The same applies to YANGI and KISS, which i would like to add.

Maybe we'll fix the error first, and then we'll think about optimization?

**Comment by TomasVotruba** [comment]
> Maybe we'll fix the error first, and then we'll think about optimization?

Agree, smaller step beats huge jump.

**Comment by peter-gribanov** [comment]
Update PR

**Comment by peter-gribanov** [comment]
@TomasVotruba please, review again
I reduced and simplified the examples
And i fixed the violation of [SRP](https://github.com/jupeter/clean-code-php#single-responsibility-principle-srp) in [current version](https://github.com/jupeter/clean-code-php#liskov-substitution-principle-lsp)

**Comment by TomasVotruba** [comment]
Thanks, now it's clear to me

**Pull request merged**
