### PR TITLE
Make objects have private/protected members

### PR DESCRIPTION
**Pull request by peter-gribanov**
I add description of @metamaker
See #75

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thanks for this addition.
It seems bit long to me just to explain the difference. Moreover compared to current document size it might tempt the reader to just skip it.

Do you think you could shorten it to its ~third and **highlight the best parts**?

**Comment by peter-gribanov** [comment]
@TomasVotruba I have shortened the text as much as possible.

**Comment by dmytro-y-dev** [comment]
> `private` methods _are guarantee_ you that code in your methods is **dangerous to modify only in boundaries of single class**

Grammar mistakes. Can be `private modifier guarantees that code is **dangerous to modify only in boundaries of single class**`.

**Comment by peter-gribanov** [comment]
@metamaker fixed

**Comment by TomasVotruba** [comment]
:+1:

**Pull request merged**
