### PR TITLE
Fix Php version for void type hinting

### PR DESCRIPTION
**Pull request by DylanDelobel**
Void Return Type was implemented in 7.1 not lower

https://wiki.php.net/rfc/void_return_type

### CODE REVIEW

**Comment by TomasVotruba** [comment]
The comment looks like reference to `string` typehint in argument, which is available since PHP 7.0. So it is correct.

Maybe add another sentence with PHP 7.1 and `void` would be more clear

**Comment by peter-gribanov** [comment]
Already there is a mention of this:

> Although many developers still use PHP 5, most of the examples in this article only work with PHP 7.1+.

**Comment by TomasVotruba** [comment]
@peter-gribanov Thanks Peter, I forgot that.

@DylanDelobel So please remove the note as whole, since it's already mentioned.

**Comment by peter-gribanov** [comment]
@TomasVotruba To delete a note is completely wrong. It is possible to rephrase.
There is a reason for this comment #26

**Comment by TomasVotruba** [comment]
I think using one single PHP version for whole docs would be the best for learning

**Comment by peter-gribanov** [comment]
My suggestion:

```diff
- If you support only PHP 7+, then you can use [type hinting](http://php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration) and be sure that the `$breweryName` will not be `NULL`.
+ You can use [type hinting](http://php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration) and be sure that the `$breweryName` will not be `NULL`.
```

**Comment by peter-gribanov** [comment]
*PR #26 was accepted before #110 and #121. That's why it happened.*

**Comment by DylanDelobel** [comment]
@peter-gribanov I like your suggestion, should I commit your sentence ?

**Comment by peter-gribanov** [comment]
@DylanDelobel Yes. Do it. Thanks 👍

**Review by peter-gribanov — APPROVED** [review]

**Comment by TomasVotruba** [comment]
Thank you both

**Pull request merged**
